[package]
name = "aoc-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1"
num = "0.4"
itertools = "0.10"
rand = "0.8"
